name: Python + Docker CI

on:
  push:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Build Docker image
        run: docker build -t python-ci-app .
      
      - name: Test Docker image
        run: docker run --rm python-ci-app
